version: '3.1'

services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=prestashop-db
    volumes:
      - ./data/prestashop:/var/www/html
    networks:
      - prestashop-net

  prestashop-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashoppass
    volumes:
      - ./data/prestashop_DB:/var/lib/mysql
    networks:
      - prestashop-net

networks:
  prestashop-net:
    driver: bridge
