<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84Cn6lu\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84Cn6lu/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container84Cn6lu.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container84Cn6lu\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container84Cn6lu\appAppKernelProdContainer([
    'container.build_hash' => '84Cn6lu',
    'container.build_id' => 'cb8355c9',
    'container.build_time' => 1718717393,
], __DIR__.\DIRECTORY_SEPARATOR.'Container84Cn6lu');
