<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4lx29D\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4lx29D/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerC4lx29D.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerC4lx29D\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerC4lx29D\appAppKernelProdContainer([
    'container.build_hash' => 'C4lx29D',
    'container.build_id' => '04793a55',
    'container.build_time' => 1718483055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4lx29D');
