<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrF6poZ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrF6poZ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXrF6poZ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXrF6poZ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXrF6poZ\appAppKernelProdContainer([
    'container.build_hash' => 'XrF6poZ',
    'container.build_id' => 'bcea667f',
    'container.build_time' => 1717651874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrF6poZ');
